supercontest/views/main.py
"""The ``main`` blueprint is the collection of all other (non-contest) views, the ones that
don't require a season or week to be specified.
"""
import logging
from typing import Any
from flask import g, Blueprint, render_template, request, redirect, url_for, Response, current_app
from werkzeug.wrappers import Response as BaseResponse
from flask_user import current_user, login_required, roles_required
import stripe
from stripe.error import SignatureVerificationError
from supercontest.dbsession import queries, commits
from supercontest.core import picks, lines, results
from supercontest.forms import EmailPreferencesForm
from supercontest.util.csrf import csrf
from supercontest.models.schemas import GameSchema
from supercontest.models import cache, Game
from supercontest.views.common import VIEW_CACHE_TTL

logger = logging.getLogger(__name__)

#: The toplevel blueprint for everything that's not a contest view.
main_blueprint = Blueprint("main", __name__)


@main_blueprint.get("/")
@login_required
def home() -> BaseResponse:
    """The home route of the application.

    :return: A redirect to the desired (actual) landing page of the app.
    """
    if g.is_preseason or g.is_regseason:
        route = "matchups.matchups"
    else:
        route = "leaderboard.leaderboard"
    return redirect(url_for(route))


@main_blueprint.get("/feedback")
@login_required
def feedback() -> str:
    """A cheeky input form for user feedback.

    :return: The rendered template for the route.
    """
    return render_template("general/feedback.html")


@main_blueprint.get("/contact")
@login_required
def contact() -> str:
    """Contact form for user communication.

    :return: The rendered template for the route.
    """
    return render_template("general/contact.html")


@main_blueprint.route("/email_preferences", methods=["GET", "POST"])
@login_required
def email_preferences() -> str | BaseResponse:
    """Form in which users can change their notifications.

    :return: The rendered template for the route (if ``GET``) or a redirect home (if ``POST``).
    """
    form: Any = EmailPreferencesForm(obj=current_user)  # flask-wtf grabs request.form
    if form.validate_on_submit():  # makes sure it's a POST and calls validate
        form.populate_obj(current_user)
        current_app.user_manager.db_manager.save_object(current_user)  # pyright: ignore
        current_app.user_manager.db_manager.commit()  # pyright: ignore
        return redirect(url_for("main.home"))
    return render_template("flask_user/email_prefs.html", form=form)


@main_blueprint.post("/pick")
@login_required
def pick() -> Response:
    """This route handles picks from the client.

    :return: A flask response.
    """
    try:
        json: dict[Any, Any] = request.json if request.json is not None else {}
        season: int = json["season"]
        week: int = json["week"]
        teams: list[str] = json["picks"]
        picks.commit_picks(
            user_id=current_user.id,
            season=season,
            week=week,
            teams=teams,
        )
    except picks.InvalidPicks as exc:
        logger.exception("Invalid picks")
        return Response(status=400, response=str(exc))
    return Response(status=200)


@main_blueprint.post("/pick_late")
@roles_required("Admin")
def pick_late() -> BaseResponse:
    """Allows an admin to submit picks late for a user.

    :return: A redirect to the allpicks view.
    :raises ValueError: If not in a current week in the regular season.
    """
    user_email_lowered = request.form["user"]
    teams = [value for key, value in request.form.items() if "picked_team" in key]
    user_id = queries.get_user_from_email(email=user_email_lowered).id
    current_season, current_week = queries.get_current_season_and_week()
    if current_season is None or current_week is None:
        raise ValueError("Can only submit late picks from Sun -> Wed of the intended week")
    picks.commit_picks(
        user_id=user_id,
        season=current_season,
        week=current_week,
        teams=teams,
        emails=[user_email_lowered],
        verify=False,
    )
    return redirect(url_for("picks.picks"))


@main_blueprint.post("/commit_lines")
@roles_required("Admin")
def commit_lines() -> BaseResponse:
    """The route which handles the line commit every wednesday evening.

    :return: A redirect to the matchups view.
    """
    lines.commit_lines()
    return redirect(url_for("matchups.matchups"))


@main_blueprint.post("/change_status")
@roles_required("Admin")
def change_status() -> BaseResponse:
    """Allows an admin to change the status of a game. This is useful when
    the scorestrip is not realtime/live.

    :return: A redirect to the matchups view.
    """
    # The matchup on the form is shaped like "<id> <favorite> vs <underdog>"
    matchup = request.form["matchup"]
    game_id = int(matchup.split()[0])
    status_name = request.form["status_name"]
    commits.change_game_status(game_id=game_id, status_name=status_name)
    return redirect(url_for("matchups.matchups"))


@main_blueprint.get("/checkout")
@login_required
def checkout() -> str | BaseResponse:
    """Route handles stripe payment.

    :return: The rendered template for the checkout route with a loaded session, or a redirect home
        (if it's the offseason or the user is already in the paid league).
    """
    if current_app.config["DEBUG"]:
        stripe_public_api_key: Any = current_app.config["STRIPE_PUBLIC_KEY_API_TEST"]
    else:
        stripe_public_api_key: Any = current_app.config["STRIPE_PUBLIC_KEY_API"]
    if queries.is_offseason():
        logger.info("It is the offseason. Upgrading to a paid account is not allowed at this time.")
        return redirect(url_for("main.home"))
    current_season = queries.get_current_season()
    paid_league_id = queries.get_paid_league_id_for_season(season=current_season)
    if queries.is_user_in_league(user_id=current_user.id, league_id=paid_league_id):
        logger.info(
            f"User {current_user.email} tried to visit /checkout but is "
            + f"already in the paid league for {current_season} "
            + f"(id {paid_league_id}). Not creating a session and not "
            + "redirecting them to stripe."
        )
        return redirect(url_for("main.home"))
    stripe_checkout_session: Any = stripe.checkout.Session
    session: Any = stripe_checkout_session.create(
        success_url=request.url_root + url_for("main.checkout_success"),
        cancel_url=request.url_root,
        customer_email=current_user.email,
        client_reference_id=current_user.id,
        payment_method_types=["card"],
        mode="payment",
        line_items=[
            {
                "price_data": {
                    "currency": "usd",
                    "unit_amount": 5000,
                    "product_data": {
                        "name": f"Upgrade to Paid League for {current_season}",
                    },
                },
                "quantity": 1,
            }
        ],
    )
    return render_template(
        "checkout/checkout.html",
        public_api_key=stripe_public_api_key,
        session_id=session.id,
    )


@main_blueprint.get("/checkout_success")
@login_required
def checkout_success() -> str:
    """If a stripe checkout was successful.

    :return: The rendered template for the route.
    """
    return render_template("checkout/checkout_success.html")


@main_blueprint.post("/checkout_confirmation")
@csrf.exempt
def checkout_confirmation() -> Response:
    """When stripe sees a completed purchase, it sends a webhook event here. If it receives 200
    from this route, then it will forward the user to the success_url.

    :return: The flask response.
    """
    # Extract the proper secret based on environment.
    if current_app.config["DEBUG"]:
        stripe_webhook_secret: Any = current_app.config["STRIPE_SECRET_KEY_WEBHOOK_TEST"]
    else:
        stripe_webhook_secret: Any = current_app.config["STRIPE_SECRET_KEY_WEBHOOK"]
    # Analyze the event.
    try:
        stripe_sig = request.headers.get("Stripe-Signature")
        event: Any = stripe.Webhook.construct_event(
            request.data.decode("utf-8"),
            stripe_sig if stripe_sig is not None else "",
            stripe_webhook_secret,
        )
    except ValueError:
        logger.exception("Error while decoding stripe event in checkout_confirmation()")
        return Response(status=400, response="Bad payload")
    except SignatureVerificationError:
        return Response(status=400, response="Bad signature")
    # Actually add the user to the paid league in the db.
    if event["type"] == "checkout.session.completed":
        session: Any = event["data"]["object"]
        email: str = session["customer_email"]
        # user_id = int(session['client_reference_id'])
        logger.info(
            f"Received checkout_confirmation webhook (id: {event.id}) from stripe for {email}"
        )
        # season and league_id should be passed through stripe too, rather than re-queried,
        # because of the tiny chance someone tries to pay right at season crossover, but
        # we don't have to worry about that.
        commits.add_user_to_current_paid_league(user_email=email)
        logger.info("Successfully added them to the Paid League table.")
    return Response(status=200)


@main_blueprint.get("/alltimelb")
@login_required
@cache.cached(VIEW_CACHE_TTL)
def alltimelb() -> str:
    """Shows all league all user all season scores.

    :return: The rendered template for the route.
    """
    final_alltime_results, toprow_seasons, toprow_alltime = results.view_alltime_leaderboard()
    return render_template(
        "contest/alltimelb.html",
        final_alltime_results=final_alltime_results,
        toprow_seasons=toprow_seasons,
        toprow_alltime=toprow_alltime,
    )


@main_blueprint.get("/games/season<season>/week<week>")
@login_required

supercontest/views/progression.py
"""The blueprint for the progression views."""
from typing import Any
from flask import Blueprint, render_template, g
from flask_user import current_user, login_required
from supercontest.core import results
from supercontest.util.plotting import form_scatter
from supercontest.views.common import url_defaults, url_value_preprocessor, VIEW_CACHE_TTL
from supercontest.models import cache

#: The blueprint for the progression views.
progression_blueprint = Blueprint("progression", __name__, url_prefix="/progression")

#: Which URL path params are required for this view.
progression_values = {
    "league": True,
    "week": False,
}


@progression_blueprint.url_defaults
def progression_url_defaults(endpoint: str, values: dict[str, Any]):
    """Wrapper for common defaults call. The ``values`` dict is mutated.

    :param endpoint: The flask endpoint.
    :param values: The flask values.
    """
    url_defaults(endpoint=endpoint, values=values, **progression_values)


@progression_blueprint.url_value_preprocessor
def progression_url_value_preprocessor(  # pylint: disable=unused-argument
    endpoint: str | None,
    values: dict[str, Any] | None,
):
    """Wrapper for common preprocessors call. Values are extracted then added to ``g``.

    :param endpoint: The flask endpoint.
    :param values: The flask values.
    """
    url_value_preprocessor(values=values, **progression_values)


@progression_blueprint.get("/season<season>/league<league>")
@login_required
@cache.cached(VIEW_CACHE_TTL)
def progression() -> str:
    """The route for a week-by-week progression graph of all scores for all users for a season.

    :return: The rendered template for the view.
    """
    sorted_season_results = results.view_progression(season=g.season, league_id=g.league)
    # Iterate over the sorted season totals and extract the information needed for scatter traces.
    if g.is_current_season_requested:
        if g.current_week is None:
            weeks = range(0)
        else:
            weeks = range(1, g.current_week + 1)
    else:
        weeks = range(1, g.weeks_in_season + 1)
    traces: list[dict[int | float, int | float]] = []
    names: list[str] = []
    visibilities: list[bool] = []
    for season_result in sorted_season_results:  # each is for a user
        traces.append(  # {week: finished_points}
            {
                week: season_result["point_rollups_by_week"].get(week, {"finished": 0})["finished"]
                for week in weeks
            }
        )
        names.append(g.id_name_map[season_result["user_id"]][:30])  # truncate so legend isn't huge
        visibilities.append(season_result["user_id"] == current_user.id)
    dumped_graph = form_scatter(
        traces=tuple(traces),
        title="Cumulative Points Over Weeks",
        names=tuple(names),
        visibilities=tuple(visibilities),
    )
    return render_template("contest/progression.html", dumped_graph=dumped_graph)

supercontest/views/statistics.py
"""The blueprint for the statistical views."""
from typing import Any
from flask import Blueprint, render_template, g
from flask_user import login_required
from supercontest.core import stats
from supercontest.views.common import url_defaults, url_value_preprocessor, VIEW_CACHE_TTL
from supercontest.models import cache

#: The blueprint for the statistical views.
statistics_blueprint = Blueprint("statistics", __name__, url_prefix="/statistics")

#: Which URL path params are required for this view.
statistics_values = {
    "league": False,
    "week": False,
    "stats_scope": True,
}


@statistics_blueprint.url_defaults
def statistics_url_defaults(endpoint: str, values: dict[str, Any]):
    """Wrapper for common defaults call. The ``values`` dict is mutated.

    :param endpoint: The flask endpoint.
    :param values: The flask values.
    """
    url_defaults(endpoint=endpoint, values=values, **statistics_values)


@statistics_blueprint.url_value_preprocessor
def statistics_url_value_preprocessor(  # pylint: disable=unused-argument
    endpoint: str | None,
    values: dict[str, Any] | None,
):
    """Wrapper for common preprocessors call. Values are extracted then added to ``g``.

    :param endpoint: The flask endpoint.
    :param values: The flask values.
    """
    url_value_preprocessor(values=values, **statistics_values)


@statistics_blueprint.get("/<stats_scope>/season<season>")
@login_required
@cache.cached(VIEW_CACHE_TTL)
def statistics() -> str:
    """Stats view. ``season=0`` means all seasons, and is cast here (``None`` means don't filter
    the subsequent query).

    :return: The rendered template for the route.
    """
    stats_builders = {
        "sbsc": stats.build_sbsc_plots,
        "nfl": stats.build_nfl_plots,
    }
    plots, numgames = stats_builders[g.stats_scope](season=g.season or None)
    return render_template("contest/stats.html", plots=plots, numgames=numgames)

supercontest/templates/navs/dropdowns/contest_view.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle btn btn-secondary" href="#" id="navDropdownView" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        View
    </a>
    <div class="dropdown-menu text-center" aria-labelledby="navDropdownView">
        {% set matchups_link = url_for('matchups.matchups', season=g.params.get('season', -1), week=g.params.get('week', -1)) %}
        <a class="dropdown-item" href="{{ matchups_link }}">Your Picks</a>
        {% set picks_link = url_for('picks.picks', season=g.params.get('season', -1), week=g.params.get('week', -1), league=g.params.get('league', -1)) %}
        <a class="dropdown-item" href="{{ picks_link }}">All Picks</a>
        {% set leaderboard_link = url_for('leaderboard.leaderboard', season=g.params.get('season', -1), league=g.params.get('league', -1)) %}
        <a class="dropdown-item" href="{{ leaderboard_link }}">Leaderboard</a>
        {% set progression_link = url_for('progression.progression', season=g.params.get('season', -1), league=g.params.get('league', -1)) %}
        <a class="dropdown-item" href="{{ progression_link }}">Progression</a>
        {% set statistics_link = url_for('statistics.statistics', stats_scope=g.params.get('stats_scope', ""), season=g.params.get('season', -1)) %}
        <a class="dropdown-item" href="{{ statistics_link }}">Statistics</a>
    </div>
</li>

supercontest/templates/navs/dropdowns/general.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navDropdownGeneral" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        General
    </a>
    <div class="dropdown-menu text-center" aria-labelledby="navDropdownGeneral">
        <a class="dropdown-item" href="https://docs.southbaysupercontest.com/en/master/rules.html" target="_blank">
            Rules
        </a>
        <a class="dropdown-item" href="https://docs.southbaysupercontest.com" target="_blank">
            Docs
        </a>
        <a class="dropdown-item" href="{{ url_for('graphql') }}" target="_blank">
            API
        </a>
        <a class="dropdown-item" href="{{ url_for('main.feedback') }}">
            Feedback
        </a>
        <a class="dropdown-item" href="{{ url_for('main.contact') }}">
            Contact
        </a>
    </div>
</li>

supercontest/templates/navs/dropdowns/league.html
{% if 'league' in g %}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navDropdownLeague" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        League
    </a>
    <div class="dropdown-menu text-center" aria-labelledby="navDropdownLeague">
        <!-- free league -->
        {% set var_param = {"league": 0} %}
        {% set free_league_link = url_for(request.url_rule.endpoint, **dict(g.params, **var_param)) %}
        <a class="dropdown-item" href="{{ free_league_link }}">Free</a>
        <!-- other leagues -->
        {% for league_id, league_name in g.available_leagues %}
            {% set var_param = {"league": league_id} %}
            {% set other_league_link = url_for(request.url_rule.endpoint, **dict(g.params, **var_param)) %}
            <a class="dropdown-item" href="{{ other_league_link }}">{{ league_name }}</a>
        {% endfor %}
    </div>
</li>

{% endif %}

supercontest/templates/navs/dropdowns/profile.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navDropdownProfile" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user"></i>
    </a>
    <div class="dropdown-menu text-center" aria-labelledby="navDropdownProfile">
        <a class="dropdown-item" href="{{ url_for('user.edit_user_profile') }}">
            Settings
        </a>
        <a class="dropdown-item" href="{{ url_for('user.logout') }}">
            Logout
        </a>
        {% if call_or_get(current_user.is_authenticated) and current_user.has_roles('Admin') %}
        <a class="dropdown-item text-danger" href="/admin" target="_blank">
            Admin
        </a>
        {% endif %}
    </div>
</li>

supercontest/templates/navs/dropdowns/season.html
{% if 'season' in g %}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navDropdownSeason" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Season
    </a>
    <div class="dropdown-menu text-center" aria-labelledby="navDropdownSeason">
        {% if 'leaderboard' in request.path %}
            <a class="dropdown-item" href="{{ url_for('main.alltimelb') }}">Alltime</a>
        {% endif %}
        {% if 'statistics' in request.path %}
            <a class="dropdown-item" href="{{ url_for('statistics.statistics', stats_scope=g.params.get('stats_scope', ''), season=0) }}">Alltime</a>
        {% endif %}
        {% for _season in g.available_seasons %}
            {% set var_param = {"season": _season} %}
            {% set other_season_link = url_for(request.url_rule.endpoint, **dict(g.params, **var_param)) %}
            <a class="dropdown-item" href="{{ other_season_link }}">{{ _season }}</a>
        {% endfor %}
    </div>
</li>

{% endif %}

supercontest/templates/navs/dropdowns/stats_scope.html
{% if 'stats_scope' in g %}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navDropdownStatsScope" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Scope
    </a>
    <div class="dropdown-menu text-center" aria-labelledby="navDropdownStatsScope">
        {% set nfl_link = url_for('statistics.statistics', stats_scope='nfl', season=g.params.get('season', -1)) %}
        <a class="dropdown-item" href="{{ nfl_link }}">NFL</a>
        {% set sbsc_link = url_for('statistics.statistics', stats_scope='sbsc', season=g.params.get('season', -1)) %}
        <a class="dropdown-item" href="{{ sbsc_link }}">SBSC</a>
    </div>
</li>

{% endif %}

supercontest/templates/navs/dropdowns/week.html
{% if 'week' in g %}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navDropdownWeek" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Week
    </a>
    <div class="dropdown-menu text-center" aria-labelledby="navDropdownWeek">
        {% if not g.is_current_season_requested %}
            {% set up_to_week = g.weeks_in_season %}
        {% else %}
            {% if g.is_regseason %}
                {% set up_to_week = g.current_week %}
            {% elif g.is_preseason %}
                {% set up_to_week = 1 %}
            {% else %}
                {% set up_to_week = g.weeks_in_season %}
            {% endif %}
        {% endif %}
        {% for _week in range(1, up_to_week + 1) %}
            {% set var_param = {"week": _week} %}
            {% set other_week_link = url_for(request.url_rule.endpoint, **dict(g.params, **var_param)) %}
            <a class="dropdown-item" href="{{ other_week_link }}">{{ '%02d' % _week }}</a>
        {% endfor %}
    </div>
</li>

{% endif %}