supercontest/views/leaderboard.py
"""The blueprint for the leaderboard views."""
from typing import Any
from flask import Blueprint, render_template, g
from flask_user import login_required
from supercontest.core import results
from supercontest.views.common import url_defaults, url_value_preprocessor, VIEW_CACHE_TTL
from supercontest.models import cache

#: The blueprint for the leaderboard views.
leaderboard_blueprint = Blueprint(
    "leaderboard",
    __name__,
    url_prefix="/leaderboard",
    template_folder="templates",
    static_folder="static",
)

#: Which URL path params are required for this view.
leaderboard_values = {
    "league": True,
    "week": False,
}


@leaderboard_blueprint.url_defaults
def leaderboard_url_defaults(endpoint: str, values: dict[str, Any]):
    """Wrapper for common defaults call. The ``values`` dict is mutated.

    :param endpoint: The flask endpoint.
    :param values: The flask values.
    """
    url_defaults(endpoint=endpoint, values=values, **leaderboard_values)


@leaderboard_blueprint.url_value_preprocessor
def leaderboard_url_value_preprocessor(  # pylint: disable=unused-argument
    endpoint: str | None,
    values: dict[str, Any] | None,
):
    """Wrapper for common preprocessors call. Values are extracted then added to ``g``.

    :param endpoint: The flask endpoint.
    :param values: The flask values.
    """
    url_value_preprocessor(values=values, **leaderboard_values)


@leaderboard_blueprint.get("/season<season>/league<league>")
@login_required
@cache.cached(VIEW_CACHE_TTL)
def leaderboard() -> str:
    """The route for all users' scores over the course of a season.

    :return: The rendered template for the view.
    """
    final_season_results, toprow_weeks, toprow_season, total_party = results.view_leaderboard(
        season=g.season,
        league_id=g.league,
    )
    return render_template(
        "contest/leaderboard.html",
        final_season_results=final_season_results,
        toprow_weeks=toprow_weeks,
        toprow_season=toprow_season,
        total_party=total_party,
    )

supercontest/views/main.py
"""The ``main`` blueprint is the collection of all other (non-contest) views, the ones that
don't require a season or week to be specified.
"""
import logging
from typing import Any
from flask import g, Blueprint, render_template, request, redirect, url_for, Response, current_app
from werkzeug.wrappers import Response as BaseResponse
from flask_user import current_user, login_required, roles_required
import stripe
from stripe.error import SignatureVerificationError
from supercontest.dbsession import queries, commits
from supercontest.core import picks, lines, results
from supercontest.forms import EmailPreferencesForm
from supercontest.util.csrf import csrf
from supercontest.models.schemas import GameSchema
from supercontest.models import cache, Game
from supercontest.views.common import VIEW_CACHE_TTL

logger = logging.getLogger(__name__)

#: The toplevel blueprint for everything that's not a contest view.
main_blueprint = Blueprint("main", __name__)


@main_blueprint.get("/")
@login_required
def home() -> BaseResponse:
    """The home route of the application.

    :return: A redirect to the desired (actual) landing page of the app.
    """
    if g.is_preseason or g.is_regseason:
        route = "matchups.matchups"
    else:
        route = "leaderboard.leaderboard"
    return redirect(url_for(route))


@main_blueprint.get("/feedback")
@login_required
def feedback() -> str:
    """A cheeky input form for user feedback.

    :return: The rendered template for the route.
    """
    return render_template("general/feedback.html")


@main_blueprint.get("/contact")
@login_required
def contact() -> str:
    """Contact form for user communication.

    :return: The rendered template for the route.
    """
    return render_template("general/contact.html")


@main_blueprint.route("/email_preferences", methods=["GET", "POST"])
@login_required
def email_preferences() -> str | BaseResponse:
    """Form in which users can change their notifications.

    :return: The rendered template for the route (if ``GET``) or a redirect home (if ``POST``).
    """
    form: Any = EmailPreferencesForm(obj=current_user)  # flask-wtf grabs request.form
    if form.validate_on_submit():  # makes sure it's a POST and calls validate
        form.populate_obj(current_user)
        current_app.user_manager.db_manager.save_object(current_user)  # pyright: ignore
        current_app.user_manager.db_manager.commit()  # pyright: ignore
        return redirect(url_for("main.home"))
    return render_template("flask_user/email_prefs.html", form=form)


@main_blueprint.post("/pick")
@login_required
def pick() -> Response:
    """This route handles picks from the client.

    :return: A flask response.
    """
    try:
        json: dict[Any, Any] = request.json if request.json is not None else {}
        season: int = json["season"]
        week: int = json["week"]
        teams: list[str] = json["picks"]
        picks.commit_picks(
            user_id=current_user.id,
            season=season,
            week=week,
            teams=teams,
        )
    except picks.InvalidPicks as exc:
        logger.exception("Invalid picks")
        return Response(status=400, response=str(exc))
    return Response(status=200)


@main_blueprint.post("/pick_late")
@roles_required("Admin")
def pick_late() -> BaseResponse:
    """Allows an admin to submit picks late for a user.

    :return: A redirect to the allpicks view.
    :raises ValueError: If not in a current week in the regular season.
    """
    user_email_lowered = request.form["user"]
    teams = [value for key, value in request.form.items() if "picked_team" in key]
    user_id = queries.get_user_from_email(email=user_email_lowered).id
    current_season, current_week = queries.get_current_season_and_week()
    if current_season is None or current_week is None:
        raise ValueError("Can only submit late picks from Sun -> Wed of the intended week")
    picks.commit_picks(
        user_id=user_id,
        season=current_season,
        week=current_week,
        teams=teams,
        emails=[user_email_lowered],
        verify=False,
    )
    return redirect(url_for("picks.picks"))


@main_blueprint.post("/commit_lines")
@roles_required("Admin")
def commit_lines() -> BaseResponse:
    """The route which handles the line commit every wednesday evening.

    :return: A redirect to the matchups view.
    """
    lines.commit_lines()
    return redirect(url_for("matchups.matchups"))


@main_blueprint.post("/change_status")
@roles_required("Admin")
def change_status() -> BaseResponse:
    """Allows an admin to change the status of a game. This is useful when
    the scorestrip is not realtime/live.

    :return: A redirect to the matchups view.
    """
    # The matchup on the form is shaped like "<id> <favorite> vs <underdog>"
    matchup = request.form["matchup"]
    game_id = int(matchup.split()[0])
    status_name = request.form["status_name"]
    commits.change_game_status(game_id=game_id, status_name=status_name)
    return redirect(url_for("matchups.matchups"))


@main_blueprint.get("/checkout")
@login_required
def checkout() -> str | BaseResponse:
    """Route handles stripe payment.

    :return: The rendered template for the checkout route with a loaded session, or a redirect home
        (if it's the offseason or the user is already in the paid league).
    """
    if current_app.config["DEBUG"]:
        stripe_public_api_key: Any = current_app.config["STRIPE_PUBLIC_KEY_API_TEST"]
    else:
        stripe_public_api_key: Any = current_app.config["STRIPE_PUBLIC_KEY_API"]
    if queries.is_offseason():
        logger.info("It is the offseason. Upgrading to a paid account is not allowed at this time.")
        return redirect(url_for("main.home"))
    current_season = queries.get_current_season()
    paid_league_id = queries.get_paid_league_id_for_season(season=current_season)
    if queries.is_user_in_league(user_id=current_user.id, league_id=paid_league_id):
        logger.info(
            f"User {current_user.email} tried to visit /checkout but is "
            + f"already in the paid league for {current_season} "
            + f"(id {paid_league_id}). Not creating a session and not "
            + "redirecting them to stripe."
        )
        return redirect(url_for("main.home"))
    stripe_checkout_session: Any = stripe.checkout.Session
    session: Any = stripe_checkout_session.create(
        success_url=request.url_root + url_for("main.checkout_success"),
        cancel_url=request.url_root,
        customer_email=current_user.email,
        client_reference_id=current_user.id,
        payment_method_types=["card"],
        mode="payment",
        line_items=[
            {
                "price_data": {
                    "currency": "usd",
                    "unit_amount": 5000,
                    "product_data": {
                        "name": f"Upgrade to Paid League for {current_season}",
                    },
                },
                "quantity": 1,
            }
        ],
    )
    return render_template(
        "checkout/checkout.html",
        public_api_key=stripe_public_api_key,
        session_id=session.id,
    )


@main_blueprint.get("/checkout_success")
@login_required
def checkout_success() -> str:
    """If a stripe checkout was successful.

    :return: The rendered template for the route.
    """
    return render_template("checkout/checkout_success.html")


@main_blueprint.post("/checkout_confirmation")
@csrf.exempt
def checkout_confirmation() -> Response:
    """When stripe sees a completed purchase, it sends a webhook event here. If it receives 200
    from this route, then it will forward the user to the success_url.

    :return: The flask response.
    """
    # Extract the proper secret based on environment.
    if current_app.config["DEBUG"]:
        stripe_webhook_secret: Any = current_app.config["STRIPE_SECRET_KEY_WEBHOOK_TEST"]
    else:
        stripe_webhook_secret: Any = current_app.config["STRIPE_SECRET_KEY_WEBHOOK"]
    # Analyze the event.
    try:
        stripe_sig = request.headers.get("Stripe-Signature")
        event: Any = stripe.Webhook.construct_event(
            request.data.decode("utf-8"),
            stripe_sig if stripe_sig is not None else "",
            stripe_webhook_secret,
        )
    except ValueError:
        logger.exception("Error while decoding stripe event in checkout_confirmation()")
        return Response(status=400, response="Bad payload")
    except SignatureVerificationError:
        return Response(status=400, response="Bad signature")
    # Actually add the user to the paid league in the db.
    if event["type"] == "checkout.session.completed":
        session: Any = event["data"]["object"]
        email: str = session["customer_email"]
        # user_id = int(session['client_reference_id'])
        logger.info(
            f"Received checkout_confirmation webhook (id: {event.id}) from stripe for {email}"
        )
        # season and league_id should be passed through stripe too, rather than re-queried,
        # because of the tiny chance someone tries to pay right at season crossover, but
        # we don't have to worry about that.
        commits.add_user_to_current_paid_league(user_email=email)
        logger.info("Successfully added them to the Paid League table.")
    return Response(status=200)


@main_blueprint.get("/alltimelb")
@login_required
@cache.cached(VIEW_CACHE_TTL)
def alltimelb() -> str:
    """Shows all league all user all season scores.

    :return: The rendered template for the route.
    """
    final_alltime_results, toprow_seasons, toprow_alltime = results.view_alltime_leaderboard()
    return render_template(
        "contest/alltimelb.html",
        final_alltime_results=final_alltime_results,
        toprow_seasons=toprow_seasons,
        toprow_alltime=toprow_alltime,
    )


@main_blueprint.get("/games/season<season>/week<week>")
@login_required

supercontest/views/matchups.py
"""The blueprint for the matchups views."""
from typing import Any
from flask import Blueprint, render_template, g
from flask_user import current_user, login_required
from supercontest.core import results
from supercontest.models.schemas import GameSchema
from supercontest.views.common import url_defaults, url_value_preprocessor

#: The blueprint for the matchups views.
matchups_blueprint = Blueprint("matchups", __name__, url_prefix="/matchups")

#: Which URL path params are required for this view.
matchups_values = {
    "league": False,
    "week": True,
}


@matchups_blueprint.url_defaults
def matchups_url_defaults(endpoint: str, values: dict[str, Any]):
    """Wrapper for common defaults call. The ``values`` dict is mutated.

    :param endpoint: The flask endpoint.
    :param values: The flask values.
    """
    url_defaults(endpoint=endpoint, values=values, **matchups_values)


@matchups_blueprint.url_value_preprocessor
def matchups_url_value_preprocessor(  # pylint: disable=unused-argument
    endpoint: str | None,
    values: dict[str, Any] | None,
):
    """Wrapper for common preprocessors call. Values are extracted then added to ``g``.

    :param endpoint: The flask endpoint.
    :param values: The flask values.
    """
    url_value_preprocessor(values=values, **matchups_values)


@matchups_blueprint.get("/season<season>/week<week>")
@login_required
def matchups() -> str:
    """The route to show all matchups for a given week, and the current user's picks.

    :return: The rendered template for the view.
    """
    sorted_games, pick_teams = results.view_matchups(
        season=g.season,
        week=g.week,
        user_id=current_user.id,
    )
    game_schema: Any = GameSchema(many=True)
    dumped_sorted_games = game_schema.dump(sorted_games)
    return render_template(
        "contest/matchups.html",
        sorted_games=sorted_games,
        dumped_sorted_games=dumped_sorted_games,
        pick_teams=pick_teams,
    )

supercontest/views/picks.py
"""The blueprint for the picks views."""
from typing import Any
from flask import Blueprint, render_template, g, jsonify, Response
from flask_user import login_required
from supercontest.core import results
from supercontest.models.schemas import GameSchema
from supercontest.views.common import url_defaults, url_value_preprocessor, VIEW_CACHE_TTL
from supercontest.models import cache

#: The blueprint for the picks views.
picks_blueprint = Blueprint("picks", __name__, url_prefix="/picks")

#: Which URL path params are required for this view.
picks_values = {
    "league": True,
    "week": True,
}


@picks_blueprint.url_defaults
def picks_url_defaults(endpoint: str, values: dict[str, Any]):
    """Wrapper for common defaults call. The ``values`` dict is mutated.

    :param endpoint: The flask endpoint.
    :param values: The flask values.
    """
    url_defaults(endpoint=endpoint, values=values, **picks_values)


@picks_blueprint.url_value_preprocessor
def picks_url_value_preprocessor(  # pylint: disable=unused-argument
    endpoint: str | None,
    values: dict[str, Any] | None,
):
    """Wrapper for common preprocessors call. Values are extracted then added to ``g``.

    :param endpoint: The flask endpoint.
    :param values: The flask values.
    """
    url_value_preprocessor(values=values, **picks_values)


@picks_blueprint.get("/season<season>/league<league>/week<week>")
@login_required
@cache.cached(VIEW_CACHE_TTL)
def picks() -> str:
    """The route to show ALL users' picks for a given week. Fails fast if picks aren't open.

    :return: The rendered template for the view.
    """
    if g.picks_open:
        return render_template("contest/picks.html")
    sorted_games, final_week_results, toprow_week_results = results.view_allpicks(
        season=g.season,
        week=g.week,
        league_id=g.league,
    )
    game_schema: Any = GameSchema(many=True)
    dumped_sorted_games = game_schema.dump(sorted_games)
    return render_template(
        "contest/picks.html",
        sorted_games=sorted_games,
        dumped_sorted_games=dumped_sorted_games,
        final_week_results=final_week_results,
        toprow_week_results=toprow_week_results,
    )


@picks_blueprint.get("/results/season<season>/league<league>/week<week>")
@login_required
@cache.cached(VIEW_CACHE_TTL)
def picks_results() -> Response:
    """The route to fetch the calculated week results for the allpicks view. Called async
    to just return the data (rather than template) in order to tick scores/results.

    :return: The list of results (rank, grade, picks, etc).
    """
    sorted_games, final_week_results, _ = results.view_allpicks(
        season=g.season,
        week=g.week,
        league_id=g.league,
    )
    game_schema: Any = GameSchema(many=True)
    dumped_sorted_games = game_schema.dump(sorted_games)
    return jsonify([dumped_sorted_games, final_week_results])

supercontest/templates/contest/alltimelb.html
{% extends "contest/view_header.html" %}

{% block contest_view_title %}Alltime Leaderboard{% endblock %}

{% block main_view %}

<script>
    const currentUserId = {{ current_user.id }};
</script>

<div class="card">
    <div class="card-body">
        <!-- Help Collapse -->
        <div id="helpCollapse" class="collapse">
            <div class="row justify-content-center mb-3">
                <div class="col-auto">
                    <div class="card">
                        <h6 class="card-header text-center">Instructions</h6>
                        <div class="card-body">
                            <p class="card-text">The alltime leaderboard only considers completed games. It does not count any in-progress games.</p>
                            <p class="card-text">This is not filtered by league; it's the free league, every user over every season.</p>
                            <p class="card-text">APM = Average Pick Margin. Your pick overcovering their line by 15 points is different than winning via 1pt over line.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Table -->
        <div class="row justify-content-center">
            <div class="col-auto">
                <div class="table-responsive text-nowrap"> 
                    <table id="alltimelbTable" class="table table-sm table-bordered table-hover table-striped align-middle text-center mb-0">
                        <thead>
                            <tr class="table-light">
                                <td colspan="2" class="border-right-thick">Leaguewide Pick Percentages <i class="fas fa-long-arrow-alt-right"></i></td>
                                {% for season_percentage in toprow_seasons %}
                                    {% if season_percentage is not none %}
                                        <td colspan="2" class="border-left-thick">{{ season_percentage }}<span class="text-body-secondary tiny">%</span></td>
                                    {% else %}
                                        <td colspan="2" class="border-left-thick"><span class="text-body-secondary">-</span></td>
                                    {% endif %}
                                {% endfor %}
                                <td class="border-left-thick">Alltime <i class="fas fa-long-arrow-alt-right"></i></td>
                                {% if toprow_alltime is not none %}
                                    <td>{{ toprow_alltime }}<span class="text-body-secondary tiny">%</span></td>
                                {% else %}
                                    <td><span class="text-body-secondary">-</span></td>
                                {% endif %}
                                <td><span class="text-body-secondary">-</span></td>
                            </tr>
                            <tr class="table-dark">
                                <th scope="col">Rank</th>
                                <th scope="col" class="border-right-thick">User</th>
                                {% for _season in g.available_seasons %}
                                    <th colspan="2" scope="col" class="border-left-thick">{{ _season }}</th>
                                {% endfor %}
                                <th scope="col" class="border-left-thick">Points</th>
                                <th scope="col">%</th>
                                <th scope="col" data-toggle="tooltip" title="Average Pick Margin">APM</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for result in final_alltime_results %}
                                <tr class="userRow" id="{{ result['user_id']|string }}">
                                    <th scope="row" class="rankCell">{{ result["rank"] }}<span class="rankSuffix text-body-secondary tiny"></span></th>
                                    <td class="w-max-200 border-right-thick" data-toggle="tooltip" title="{{ g.id_name_map[result['user_id']] }} ({{ g.id_email_map[result['user_id']] }})">{{ g.id_name_map[result["user_id"]] }}</td>
                                    {% for _season in g.available_seasons %}
                                        {% if _season in result["pick_counts_by_season"] and _season in result["point_rollups_by_season"] %}
                                            {% set numPicks = result["pick_counts_by_season"][_season]["cover"] + result["pick_counts_by_season"][_season]["push"] + result["pick_counts_by_season"][_season]["noncover"] %}
                                            {% set points = result["point_rollups_by_season"][_season]["finished"] %}
                                            <td class="border-left-thick" data-toggle="tooltip" title="points">
                                                <a href="https://southbaysupercontest.com/leaderboard/season{{_season}}/league0" style="text-decoration: none;">
                                                    {{ points }}
                                                </a>
                                            </td>
                                            <td data-toggle="tooltip" title="percentage picks correct">
                                                <a href="https://southbaysupercontest.com/leaderboard/season{{_season}}/league0" style="text-decoration: none;">
                                                    {{ get_percentage(points, numPicks) }}<span class="text-body-secondary tiny">%</span>
                                                </a>
                                            </td>
                                        {% else %}
                                            <td class="border-left-thick"><span class="text-body-secondary">-</span></td>
                                            <td><span class="text-body-secondary">-</span></td>
                                        {% endif %}
                                    {% endfor %}
                                    <th scope="row" class="totalScore border-left-thick">{{ result["points"] }}</th>
                                    {% if result["percentage"] is not none %}
                                        <td class="percentage">{{ result["percentage"] }}<span class="text-body-secondary tiny">%</span></td>
                                    {% else %}
                                        <td><span class="text-body-secondary">-</span></td>
                                    {% endif %}
                                    <td>{{ result["avg_pick_margin"]|round(3) }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

supercontest/templates/contest/matchups.html
{% extends "contest/view_header.html" %}

{% from "macros.html" import render_main_legend %}

{% block contest_view_title %}Matchups{% endblock %}

{% block contest_view_subtitle %}{{ g.season }} Season, Week {{ g.week }}{% endblock %}

{% block main_view %}

<script>
    let flashedMessages = {{ get_flashed_messages(with_categories=true)|tojson }};
    let sortedGames = {{ dumped_sorted_games|tojson }};
    const pickTeams = {{ pick_teams|tojson }};
    const picksOpen = {{ g.picks_open|tojson }};
    const week = {{ g.week }};
    const season = {{ g.season }};
</script>

<div class="card">
    <div class="card-body">
        <!-- Help Collapse-->
        <div id="helpCollapse" class="collapse">
            <div class="row justify-content-center mb-3">
                <div class="col-auto">
                    <div class="card">
                        <h6 class="card-header text-center">Instructions</h6>
                        <div class="card-body">
                            {% if g.picks_open %}
                                <p class="card-text">For general instructions on how to pick against spreads, see the <a href="https://docs.southbaysupercontest.com/en/master/rules.html">Rules</a> page.</p>
                                <p class="card-text">Select 5 teams by clicking on their names below.</p>
                                <p class="card-text">You can change your 5 picks as much as you want until lockdown, which is Saturday nights at midnight.</p>
                                <p class="card-text">All games that occur before Sunday can be picked until kickoff. This includes standard TNF, the multiple Thanksgiving Thursday games, and the end-of-season Saturday games. You may pick early game(s) and then wait to submit your other pick(s) later.</p>
                                <p class="card-text">If you have not submitted the full 5 picks by 5pm on Saturday, the app can email you a reminder (<a href="{{ url_for('main.email_preferences') }}">notification preferences</a>).</p>
                            {% else %}
                                <p class="card-text">Picks are closed from Saturday night at midnight until Wednesday evening ~5pm (PT).</p>
                                <p class="card-text">Reach out at <a href="{{ url_for('main.contact') }}">Contact</a> if you have a justified late-pick excuse.</p>
                                <p class="card-text">Table data ticks every minute here (scores, statuses, etc), no need to refresh.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {{ render_main_legend(view='yourpicks') }}
        </div>
        <!-- Main Table -->
        {% if sorted_games|length == 0 %}
        <div class="text-center">
            <span>The app has not pulled the lines yet for week {{ g.week }}. Check back after 6pm PT.</span>
        </div>
        {% else %}
        <div class="row justify-content-center">
            <div class="col-auto">
                <div class="table-responsive text-nowrap">
                    <table class="table table-sm table-bordered table-hover align-middle text-center mb-0">
                        <thead class="table-dark">
                            <tr>
                                <th scope="col">Time (PT)</th>
                                <th scope="col" class="border-right-thick">Location</th>
                                <th scope="col" colspan="4">Favorite</th>
                                <th scope="col" colspan="4">Underdog</th>
                                <th scope="col" class="border-left-thick">Status</th>
                            </tr>
                        </thead>
                        <tbody id="matchupsTable">
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% if g.picks_open %}
            <div class="text-center mt-3">
                <button id="pick5Rrandom" type="submit" class="btn btn-primary">Pick 5 Random</button>
            </div>
        {% endif %}
        {% endif %}
    </div>
</div>

{% endblock %}

supercontest/templates/contest/progression.html
{% extends "contest/view_header.html" %}

{% block contest_view_title %}Progression{% endblock %}

{% block contest_view_subtitle %}{{ g.season }} Season, {{ g.league_name }} League{% endblock %}

{% block main_view %}

<script>
    const userInLeague = {{ g.user_in_league|tojson }};
    let flashedMessages = {{ get_flashed_messages(with_categories=true)|tojson }};
    const dumpedGraph = {{ dumped_graph|safe }};
</script>

<div class="card">
    <div class="card-body p-0">
        <!-- Help Collapse-->
        <div id="helpCollapse" class="collapse">
            <div class="row justify-content-center">
                <div class="col-auto">
                    <div class="card m-3">
                        <h6 class="card-header text-center">Instructions</h6>
                        <div class="card-body">
                            <p class="card-text">Click on any name(s) in the legend to overlay their progress onto yours. The list is in the same order as the current leaderboard.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Plot -->
        <div class="me-5" id="plotGraph"></div>
    </div>
</div>

{% endblock %}

supercontest/templates/contest/stats.html
{% extends "contest/view_header.html" %}

{% block contest_view_title %}Statistics{% endblock %}

{% block contest_view_subtitle %}
{% if g.season == 0 %}
    {{ g.stats_scope.upper() }}, All Seasons, {{ "{:,}".format(numgames) }} Games
{% else %}
    {{ g.stats_scope.upper() }}, {{ g.season }} Season, {{ "{:,}".format(numgames) }} Games
{% endif %}
{% endblock %}

{% block main_view %}

<script>
    const plots = {{ plots|tojson }};
</script>

<div class="card">
    <div class="card-body" >
        <div class="card-header text-center"><h5>Contents</h5></div>
        <ul class="mt-4 scrollbox" id="plots-toc"></ul>
    </div>
    <hr>
    <div class="card-body p-0" id="plots-card"></div>
</div>

{% endblock %}

supercontest/templates/contest/view_header.html
{% extends "bases/contest.html" %}

{% block contest_view_header %}

<nav class="navbar navbar-expand-sm bg-secondary px-3" data-bs-theme="dark">
    <span class="navbar-brand">
        {% block contest_view_title %}
        {% endblock %}
    </span>
    <span class="navbar-text me-auto">
        {% block contest_view_subtitle %}
        {% endblock %}
    </span>
    <a class="btn btn-info ms-auto" data-bs-toggle="collapse" href="#helpCollapse" aria-expanded="false" aria-controls="helpCollapse">
        Help
    </a>
</nav>

{% endblock %}